### ISSUE TITLE
Adblocker will cause the `import` to throw error

### ISSUE THREAD

**Issue by zhuhang-jasper** [sooro-io/react-gtm-module#4]
Im using it in my react project. When adblocker is present, the import of this library will break the app.
(This already happending in the original `react-gtm-module`)

```
// main.jsx
...
import "@configs/analytics/gtm";
...
```

```
//gtm.js
import TagManager from "@sooro-io/react-gtm-module"; <-- this line will break

TagManager.initialize(...);
```

![image](https://github.com/user-attachments/assets/ccfad7d4-7c11-40cf-86b9-75db9481f636)

**Comment by zhuhang-jasper** [comment]
Ok, this seems to be a `vite` issue:
https://github.com/vitejs/vite/issues/4797

**Comment by chrism1996** [comment]
Please, @zhuhang-jasper  close the issue, it cant be fixed. Turn off browser extensions in dev mode
